# Site settings
title: kevin anker
description: living and tinkering in hamburg
# baseurl: "/"
# url: "localhost:3000"

# User settings
username: kevin anker
user_title: data scientist
user_description: living and tinkering in hamburg
email: e@mail.com
github_url: https://github.com/kjanker
linkedin_url: https://www.linkedin.com/in/kjanker
xing_url: https://www.xing.com/profile/Kevin_Anker
twitter_url: https://twitter.com/kevanker

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
